services:
  frontend:
    container_name: frontend
    image: ghcr.io/tyskanhik/film-react-nest/frontend:latest
    volumes:
      - frontend_dist:/app/dist
    networks:
      - webnet
    environment:
      - VITE_API_URL=http://tyskanhik.nomorepartiesco.ru/api/afisha
      - VITE_CDN_URL=http://tyskanhik.nomorepartiesco.ru/content/afisha

  backend:
    container_name: backend
    image: ghcr.io/tyskanhik/film-react-nest/backend:latest
    environment:
        - DATABASE_DRIVER=postgres
        - DATABASE_URL=postgres
        - DATABASE_PORT=5432
        - DATABASE_USERNAME=postgres
        - DATABASE_PASSWORD=postgres
        - DATABASE_NAME=prac
    ports:
      - 3000:3000
    networks:
      - webnet
    depends_on:
      - postgres

  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prac
    volumes:
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - postgres_data:/usr/local/pgsql/data
    networks:
      - webnet

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - webnet
    environment:
      - PGADMIN_DEFAULT_EMAIL=tyskanhik1@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=postgres

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - frontend_dist:/var/www/frontend:ro
    depends_on:
     - backend
     - frontend

  certbot:
    image: certbot/certbot:latest
    networks:
      - webnet
    restart: unless-stopped
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  pgadmin-data:
  frontend_dist:

networks:
  webnet: