name: Build and Publish Docker Images

on:
  push:
    branches:
      - review-3
  pull_request:
    branches:
      - review-3
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
          build-args: |
            FRONTEND_IMAGE=./frontend
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache